name: Sync benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'integeration_test/benchmark.md'

jobs:
  sync-benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes to the repository
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Inject benchmark into README
        run: |
          sed -e '/<!-- BEGIN BENCHMARK -->/ {
            r integeration_test/benchmark.md
            d
          }' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit README changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync benchmark into README"
